### ISSUE TITLE
Code optimization questions/recomendations (SIMD support, LLVM version)

### ISSUE THREAD

**Issue by FFY00** [libmir/mir-glas#31]
Hello, I am planning to user mir-glas for a project that needs to quickly process a huge amount of data. Binary compatibility across multiple systems is not an issue, so we are free to use SIMD instructions. How is SIMD implemented in mir-glas? Do I need to enable anything special? And while I'm on it, what LLVM is recommended for the most performance? Any other thing I should have in mind?

Thank you,
Filipe

**Comment by 9il** [comment]
Hi Filipe,
Mir GLAS isn't supported anymore (just because I don't have  time to implement all features).
You may want to use [mir-blas](https://github.com/libmir/mir-blas) (bindings to BLAS libraries like OpenBLAS or Intel MKL).
See also the wiki page https://github.com/libmir/mir-lapack/wiki/Link-with-CBLAS-&-LAPACK
